[package]
name = "todayiwill"
version = "0.0.0"
edition = "2021"

[dependencies]
assert_cmd = "2.0.14"
cargo-llvm-cov = "0.6.10"
chrono = "0.4.38"
clap = { version = "4.5.7", features = ["derive"] }
dirs = "5.0.1"
serial_test = "3.1.1"
