[package]
name = "todayiwill"
version = "0.0.0"
edition = "2021"

[dependencies]
assert_cmd = "2.0.14"
cargo-llvm-cov = "0.6.10"
clap = { version = "4.5.7", features = ["derive"] }
clippy = "0.0.302"
dirs = "5.0.1"
