name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: rust:1.79-slim
    defaults:
      run:
        working-directory: ./todayiwill
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add rust packages
        run: rustup component add clippy rustfmt

      - name: Format check
        run: cargo fmt --check

      - name: Lint Check
        run: cargo clippy -- -D warnings

      - name: Tests
        run: cargo test

      - name: Build Check
        run: cargo build

      - name: Test coverage report
        id: coverage  
        uses: actions-rs/grcov@v0.1

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
