name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: rust:1.79-slim
    defaults:
      run:
        working-directory: ./todayiwill
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add rust packages
        run: rustup component add clippy rustfmt

      - name: Format check
        run: cargo fmt --check

      - name: Lint Check
        run: cargo clippy -- -D warnings

      - name: Tests
        run: cargo test -- --test-threads=1

      - name: Build Check
        run: cargo build

  coverage:
    needs: ci
    runs-on: ubuntu-latest
    container: rust:1.79-slim
    defaults:
      run:
        working-directory: ./todayiwill
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install dependencies for Codecov
        run: >
          apt-get install --no-install-recommends --yes
          ca-certificates curl git gpg gpg-agent

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
