name: Release workflow

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04]

    defaults:
      run:
        working-directory: ./todayiwill

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set version
        run: |
          VERSION=${{ github.ref_name }}
          sed -i "s/^version =.*/version = \"${VERSION:1}\"/g" Cargo.toml

      - name: Build
        run: cargo build --release

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ./todayiwill/target/release
            ./install*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: artifacts

      - name: List artifacts generated
        run: ls ./artifacts/**/*

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux executable to release
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: ${{ github.ref_name }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifacts/todayiwill
          file_glob: true
          draft: true
          body: |
            # Changelog

            ${{ steps.github_release.outputs.changelog }}

      - name: Upload installer to release
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: ${{ github.ref_name }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifacts/install-linux-debian.sh
          file_glob: true
          draft: true
