name: Release workflow

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04]

    defaults:
      run:
        working-directory: ./todayiwill

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set version
        run: sed -i "s/^version =.*/version = \"${{ github.ref_name }}\"/g" Cargo.toml

      - name: Version check
        run: cat Cargo.toml

      - name: Build
        run: cargo build --release

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: target/release

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            # Changelog

            ${{ steps.github_release.outputs.changelog }}
          draft: true
          prerelease: false

      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: artifacts

      - name: List artifacts generated
        run: ls ./artifacts/**/*

      - name: Upload linux executable to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifacts/todayiwill
          file_glob: true
