name: Release workflow

on:
  push:
    # tags:
    #   - '*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: |
          make VERSION=v0.0.0 build

      - name: Build doc
        run: |
          make build-doc

      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: ./todayiwill/target/doc

      - name: Build deb package
        run: |
          sudo apt-get install ruby-dev build-essential
          sudo gem install --no-document fpm
          make VERSION=v0.0.0 build-deb

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ./todayiwill/target/release
            ./todayiwill_*.deb
            ./install-*
            ./uninstall-*
