name: Release workflow

on:
  push:
    # tags:
    #   - '*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04]

    defaults:
      run:
        working-directory: ./todayiwill

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set version
        run: |
          # VERSION=${{ github.ref_name }}
          VERSION=v0.0.0
          sed -i "s/^version =.*/version = \"${VERSION:1}\"/g" Cargo.toml

      - name: Build
        run: cargo build --release

      - name: Build doc
        run: cargo doc --no-deps

      - name: Add redirect
        run: echo '<meta http-equiv="refresh" content="0;url=todayiwill/index.html">' > target/doc/index.html

      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: ./todayiwill/target/doc

      - name: Build deb package
        run: |
          cd ..
          sudo apt-get install ruby-dev build-essential
          sudo gem install --no-document fpm
          VERSION=0.0.0 make build-deb

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ./todayiwill/target/release
            ./install-*
            ./uninstall-*
